### ISSUE TITLE
Need this hunter in c or c++ so it will work faster

### ISSUE THREAD

**Issue by Akdxdx** [Mizogg/Hunting-with-PyQt5#2]
Hello
I tried the app and i liked the concept of this app and then i thought it will be more productive if you can write in c or c++
What you think can i expect this in future?

**Comment by Mizogg** [comment]
Hi Glad you like it. I would have to learn another code other than python to do this. I have many programs in python TKinter version is also a nice GUI interface but I think the QT is faster. 
I would like to add multi threading to improve speed and I have a few more ideas to add so keep watching.
Thanks

**Comment by Akdxdx** [comment]
I tried that qt version also that was nice creations too but speed of it also not efficient as c++ i tried vanitygen gui SifterBTC that is more then 30x faster and i googled about speed of python so it comes that python is slow in execution then Java or c++ and qt version also produce same speed as i compared tkinter power and qt version many time and deeply tested so speed is similar somewhere i like mostly the page method like keys.lol because is decreases decimals if we put long page size like i edited it to 100k per page but then it works very slow so what I think if we increase per page keys to 500k then it will same time reduce decimals of hunting range and if this app comes in c++ it can be possible so hunting will be more productive and there would be more possiblities of become a winner u might get i what am saying

**Comment by Akdxdx** [comment]
i measured speed of tkinter power and qt hunter both are giving 32k to 36k keys maximum per second on my old laptop
,You should try convert python code to c or Java by facebook's Ai code translator i read tutorial about this but a i dont have coding knowledge so i didn't tried it or what you think if this python can be complied for Android if it can provide same as pc speed it's good because as we have multiple phones we can run the apk in background for hunting 24x7
