### ISSUE TITLE
Launching programs

### ISSUE THREAD

**Issue by AnutaOk** [Mizogg/Hunting-with-PyQt5#3]
Good evening! I copied your program. I can't start it. I was able to install PyQt5, PyQt5 sip, PyQt6-sip. I'm not a programmer. I really wanted to install YOUR program. I can't install PyQt6. I can't turn on ICE.bat. I don't understand how to run the programs. Help please. Explain in detail how to use your programs

**Comment by Mizogg** [comment]
Hi Good Evening,

I am using Windows computer and have tried on 10&11. Please make sure that  the 2 programs below are installed.

Microsoft Build Tools. https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019
![image](https://github.com/Mizogg/Hunting-with-PyQt5-and-PyQt6/assets/88630056/5ea056e9-0d6f-466e-b625-e6df1df4e6b7)

Python 3.11 https://www.python.org/downloads/

With out seeing you error message I don't know why you can not run PyQt6
Here there Website
https://pypi.org/project/PyQt6/
To Install
pip install PyQt6

All of the functions within this program have been added to https://github.com/Mizogg/TeamHunter maybe give this a try.

Thanks Mizogg

**Comment by AnutaOk** [comment]
Good evening. 1 I have installed Microsoft Build Tools. There were no such packages. 2 changed python to 3.11. 3. Downloaded the packages that were included. 4 installed a dark theme from the command line. QT_main_ICE_Display.py it does not start. The program writes:
 import sys
import random
from PyQt6.QtCore import *
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from bloomfilter import BloomFilter, ScalableBloomFilter, SizeGrowthRate
import secp256k1 as ice
import time

5 The field for filling in the command gives an error: C:\python\python.exe C:\Users\user\PycharmProjects\Hunting-with-PyQt5-and-PyQt6\QT_main_ICE_Display.py
Backtracking (most recent call):
File "C:\Users\user\PycharmProjects\Hunting-with-PyQt5-and-PyQt6\QT_main_ICE_Display.py ", line 14, in <module>
with open('btc.bf ', "rb") as fp:
^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Error 2] There is no such file or directory: 'btc.bf'

Another exception occurred while processing the above exception:

Backtracking (last last call):
File "C:\Users\user\PycharmProjects\Hunting-with-PyQt5-and-PyQt6\QT_main_ICE_Display.py ", line 19, in <module>
with open(file name) as the file:
^^^^^^^^^^^^^^
FileNotFoundError: [Error 2] There is no such file or directory: 'btc.txt'

The process is completed with exit code 1
6 the program /TeamHunter_GUI is working fine for me
